name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          SPACE：   ${{ ALYUN_NAME_SPACE }}
          registry: ${{ ALIYUN_REGISTRY }}
          username: ${{ ALIYUN_REGISTRY_USER }}
          password: ${{ ALIYUN_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t my-image .
          docker tag my-image ${{ secrets.ALIYUN_REGISTRY }}/my-image
          docker push ${{ secrets.ALIYUN_REGISTRY }}/my-image
